# Generated by Django 6.0.6 on 2026-06-15 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0002_counselorprofile_booking_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofile',
            name='certificate_photo',
            field=models.FileField(blank=True, null=True, upload_to='counselor_docs/'),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='government_id',
            field=models.FileField(blank=True, null=True, upload_to='counselor_docs/'),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='counselor_docs/'),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_counselors', to=settings.AUTH_USER_MODEL),
        ),
    ]
