# Generated by Django 6.0.6 on 2026-07-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0005_payment_gateway_payment_khalti_pidx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='jitsi_room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
